// Package message defines shared message types used across envoy components.
package message

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"time"
)

// Direction indicates whether a message was received from an external sender
// or generated internally for outbound journaling.
type Direction string

const (
	DirectionInbound  Direction = "inbound"
	DirectionOutbound Direction = "outbound"
)

// InboundMessage represents an email message received by the SMTP server.
type InboundMessage struct {
	// ID is a unique identifier for this message, generated by NewID.
	ID string

	// ReceivedAt is the time the message was accepted by the SMTP server.
	ReceivedAt time.Time

	// Direction indicates the flow of the message.
	Direction Direction

	// EnvelopeFrom is the RFC 5321 MAIL FROM address.
	EnvelopeFrom string

	// EnvelopeTo holds all RFC 5321 RCPT TO addresses.
	EnvelopeTo []string

	// Domain is the matched domain from the server configuration.
	Domain string

	// RawMessage holds the full RFC 5322 message bytes verbatim.
	RawMessage []byte
}

// NewID generates a unique message identifier in the format:
//
//	ENV-<yyyymmddThhmmss>-<8-byte random hex>
//
// The result is safe for use in mail headers (no whitespace or special chars).
func NewID() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand failure is unrecoverable on any normal system.
		panic(fmt.Sprintf("message.NewID: crypto/rand unavailable: %v", err))
	}
	ts := time.Now().UTC().Format("20060102T150405")
	return "ENV-" + ts + "-" + hex.EncodeToString(b[:])
}
